<?php

namespace Database\Seeders;

use App\Models\Gym\Exercise;
use Illuminate\Database\Seeder;

class GymExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            [
                'name' => 'Sentadilla con barra',
                'description' => 'Ejercicio compuesto para tren inferior.',
                'exercise_type' => 'fuerza',
                'category' => 'dominante_rodilla',
                'muscle_groups' => ['piernas', 'gluteos'],
                'target_muscle_groups' => ['cuadriceps', 'gluteo mayor'],
                'movement_pattern' => 'squat',
                'equipment' => 'barra',
                'difficulty_level' => 'intermediate',
                'tags' => ['tren_inferior', 'intermedio', 'tecnica'],
                'instructions' => 'Mantener columna neutra, bajar hasta paralelo.',
                'is_active' => true,
            ],
            [
                'name' => 'Press banca',
                'description' => 'Empuje horizontal con barra.',
                'exercise_type' => 'fuerza',
                'category' => 'empuje_vertical_horizontal',
                'muscle_groups' => ['pecho', 'triceps', 'hombros'],
                'target_muscle_groups' => ['pectoral mayor', 'triceps', 'deltoides anterior'],
                'movement_pattern' => 'push horizontal',
                'equipment' => 'barra',
                'difficulty_level' => 'intermediate',
                'tags' => ['tren_superior', 'intermedio'],
                'instructions' => 'Pausa breve en el pecho, codos a 45°.',
                'is_active' => true,
            ],
            [
                'name' => 'Peso muerto',
                'description' => 'Patrón de bisagra de cadera.',
                'exercise_type' => 'fuerza',
                'category' => 'dominante_cadera',
                'muscle_groups' => ['piernas', 'espalda', 'gluteos'],
                'target_muscle_groups' => ['isquiotibiales', 'gluteo mayor', 'erectores espinales'],
                'movement_pattern' => 'hinge',
                'equipment' => 'barra',
                'difficulty_level' => 'intermediate',
                'tags' => ['tren_inferior', 'potencia'],
                'instructions' => 'Mantener la barra pegada a las piernas.',
                'is_active' => true,
            ],
            [
                'name' => 'Remo con mancuernas',
                'description' => 'Tracción horizontal unilateral.',
                'exercise_type' => 'fuerza',
                'category' => 'traccion_vertical_horizontal',
                'muscle_groups' => ['espalda', 'biceps'],
                'target_muscle_groups' => ['dorsal ancho', 'romboides'],
                'movement_pattern' => 'pull horizontal',
                'equipment' => 'mancuernas',
                'difficulty_level' => 'beginner',
                'tags' => ['tren_superior', 'principiante'],
                'instructions' => 'Escápulas retraídas, torso estable.',
                'is_active' => true,
            ],
            [
                'name' => 'Press militar',
                'description' => 'Empuje vertical de hombros.',
                'exercise_type' => 'fuerza',
                'category' => 'empuje_vertical_horizontal',
                'muscle_groups' => ['hombros', 'triceps'],
                'target_muscle_groups' => ['deltoides', 'triceps'],
                'movement_pattern' => 'push vertical',
                'equipment' => 'barra',
                'difficulty_level' => 'intermediate',
                'tags' => ['tren_superior'],
                'instructions' => 'Glúteos y abdomen firmes.',
                'is_active' => true,
            ],
            [
                'name' => 'Dominadas',
                'description' => 'Tracción vertical con peso corporal.',
                'exercise_type' => 'fuerza',
                'category' => 'traccion_vertical_horizontal',
                'muscle_groups' => ['espalda', 'biceps'],
                'target_muscle_groups' => ['dorsal ancho', 'biceps'],
                'movement_pattern' => 'pull vertical',
                'equipment' => 'peso corporal',
                'difficulty_level' => 'advanced',
                'tags' => ['tren_superior', 'avanzado'],
                'instructions' => 'Mentón por encima de la barra, control.',
                'is_active' => true,
            ],
            [
                'name' => 'Zancadas',
                'description' => 'Desplante unilateral.',
                'exercise_type' => 'fuerza',
                'category' => 'dominante_rodilla',
                'muscle_groups' => ['piernas', 'gluteos'],
                'target_muscle_groups' => ['cuadriceps', 'gluteo mayor'],
                'movement_pattern' => 'lunge',
                'equipment' => 'mancuernas',
                'difficulty_level' => 'beginner',
                'tags' => ['tren_inferior', 'principiante'],
                'instructions' => 'Paso largo, rodilla alineada.',
                'is_active' => true,
            ],
            [
                'name' => 'Plancha',
                'description' => 'Ejercicio isométrico de core.',
                'exercise_type' => 'estabilidad',
                'category' => 'anti_extension',
                'muscle_groups' => ['core'],
                'target_muscle_groups' => ['abdominales', 'erectores espinales'],
                'movement_pattern' => 'anti-extension',
                'equipment' => 'peso corporal',
                'difficulty_level' => 'beginner',
                'tags' => ['core', 'principiante'],
                'instructions' => 'Cuerpo en línea, glúteos activos.',
                'is_active' => true,
            ],
            [
                'name' => 'Curl bíceps con mancuernas',
                'description' => 'Aislamiento de bíceps.',
                'exercise_type' => 'fuerza',
                'category' => 'accesorios_mmss',
                'muscle_groups' => ['biceps'],
                'target_muscle_groups' => ['biceps braquial'],
                'movement_pattern' => 'curl',
                'equipment' => 'mancuernas',
                'difficulty_level' => 'beginner',
                'tags' => ['tren_superior', 'principiante'],
                'instructions' => 'Codos pegados al torso, control.',
                'is_active' => true,
            ],
            [
                'name' => 'Bicicleta estática',
                'description' => 'Trabajo cardiovascular en bicicleta.',
                'exercise_type' => 'resistencia',
                'category' => 'bicicleta',
                'muscle_groups' => ['piernas'],
                'target_muscle_groups' => ['cuadriceps', 'isquiotibiales'],
                'movement_pattern' => 'cycling',
                'equipment' => 'bicicleta',
                'difficulty_level' => 'beginner',
                'tags' => ['tren_inferior', 'rehabilitacion'],
                'instructions' => 'Mantener cadencia constante y postura erguida.',
                'is_active' => true,
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::updateOrCreate(
                ['name' => $exercise['name']],
                $exercise
            );
        }
    }
}
